/**
 * Shared helpers for sync/prune scripts (Node).
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(__dirname, "..", "..");
export const DATA_DIR = join(ROOT, "data");
export const JOBS_JSON = join(DATA_DIR, "jobs.json");
export const COMPANIES_JSON = join(DATA_DIR, "companies.json");
export const TAGS_JSON = join(DATA_DIR, "tech-tags.json");
export const JOBS_DATA_JS = join(ROOT, "js", "jobs-data.js");

export function loadJson(path, fallback = []) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

export function saveJson(path, data) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + "\n", "utf8");
}

export function jobKey(job) {
  return `${String(job.id || "").toLowerCase()}`;
}

export function dedupeKey(job) {
  return `${(job.title || "").toLowerCase().trim()}|${(job.company || "").toLowerCase().trim()}`;
}

export function loadJobs() {
  return loadJson(JOBS_JSON, []);
}

export function saveJobs(jobs) {
  saveJson(JOBS_JSON, jobs);
  generateJobsDataJs();
}

/** Regenerate js/jobs-data.js from data/*.json */
export function generateJobsDataJs() {
  const jobs = loadJson(JOBS_JSON, []);
  const companies = loadJson(COMPANIES_JSON, []);
  const tags = loadJson(TAGS_JSON, []);

  const body = `/**
 * remotedevelopers — job listings data
 *
 * AUTO-GENERATED by scripts/sync-jobs.mjs / scripts/prune-jobs.mjs
 * Source of truth: data/jobs.json, data/companies.json, data/tech-tags.json
 * Do not edit this file by hand — edit data/*.json or run the scripts.
 *
 * FUTURE SYNC: Airtable / Google Sheets can write into data/jobs.json the same way.
 */

window.RD_JOBS = ${JSON.stringify(jobs, null, 2)};

window.RD_COMPANIES = ${JSON.stringify(companies, null, 2)};

window.RD_TECH_TAGS = ${JSON.stringify(tags, null, 2)};
`;

  writeFileSync(JOBS_DATA_JS, body, "utf8");
}

export function stripHtml(html) {
  return String(html || "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

export function descFields(htmlOrText) {
  if (!htmlOrText) return { description: undefined, descriptionHtml: undefined };
  const raw = String(htmlOrText);
  const looksHtml = /<[a-z][\s\S]*>/i.test(raw);
  return {
    descriptionHtml: looksHtml ? raw : undefined,
    description: stripHtml(raw).slice(0, 500) || undefined,
  };
}

export function fmtSalary(min, max, currency, period) {
  const cur = currency || "USD";
  const sym = cur === "USD" ? "$" : `${cur} `;
  const p = (period || "").toLowerCase();
  const suffix = p.includes("hour") ? "/hr" : p.includes("month") ? "/mo" : "";
  const fmt = (n) => {
    if (n == null || n === 0) return null;
    if (n >= 1000 && !suffix) return `${sym}${Math.round(n / 1000)}k`;
    return `${sym}${Number(n).toLocaleString()}`;
  };
  const a = fmt(min);
  const b = fmt(max);
  if (a && b) return `${a} – ${b}${suffix}`;
  if (a) return `From ${a}${suffix}`;
  if (b) return `Up to ${b}${suffix}`;
  return null;
}

export function mapLevel(raw) {
  const s = Array.isArray(raw) ? raw.join(" ") : String(raw || "");
  const t = s.toLowerCase();
  if (/lead|staff|principal|director|executive|head|manager|vp/.test(t))
    return "Lead";
  if (/senior|sr\.|mid-senior/.test(t)) return "Senior";
  if (/junior|entry|intern|graduate|jr\./.test(t)) return "Junior";
  if (/mid|intermediate/.test(t)) return "Mid";
  return "Mid";
}

export function mapType(raw) {
  const t = String(Array.isArray(raw) ? raw[0] : raw || "").toLowerCase();
  if (/contract|freelance|consultant/.test(t)) return "Contract";
  return "Full-time";
}

const TECH_HINT =
  /\b(engineer|developer|devops|frontend|front-end|backend|back-end|full[\s-]?stack|software|sre|platform|mobile|ios|android|react|typescript|javascript|python|golang|rust|kubernetes|machine learning|ml engineer|data engineer|data scientist|qa engineer|security engineer|cloud|infra|programmer|coding|web developer|staff engineer|principal engineer|architect|airflow|terraform)\b/i;

export function isTechJob(title, tags) {
  if (TECH_HINT.test(title || "")) return true;
  const joined = (tags || []).join(" ");
  if (TECH_HINT.test(joined)) return true;
  const lower = (tags || []).map((t) => String(t).toLowerCase());
  return lower.some((t) =>
    [
      "dev",
      "eng",
      "software",
      "engineer",
      "developer",
      "javascript",
      "typescript",
      "python",
      "react",
      "node",
      "java",
      "golang",
      "rust",
      "devops",
      "sre",
      "frontend",
      "backend",
      "full stack",
      "fullstack",
      "web development",
      "it",
      "gcp",
      "aws",
    ].includes(t)
  );
}

export function pickTags(list) {
  const out = [];
  const seen = new Set();
  for (const item of list || []) {
    if (!item) continue;
    const raw = String(item).replace(/&amp;/g, "&").trim();
    if (!raw || raw.length > 40) continue;
    const key = raw.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(raw);
    if (out.length >= 8) break;
  }
  return out;
}

export async function fetchJSON(url, opts = {}) {
  const res = await fetch(url, {
    ...opts,
    headers: {
      Accept: "application/json",
      "User-Agent": "RemoteDevelopers.work-sync/1.0",
      ...(opts.headers || {}),
    },
  });
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return res.json();
}
